# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

parameters:
  - name: 'tenant_process_type'
    type: string
  - name: 'tenant_name'
    type: string
  - name: 'tenant_size'
    type: number
  - name: 'tenant_name'
    type: string
  - name: 'tenant_localization'
    type: string
  - name: 'tenant_initial_date'
    type: string

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    make deploy ${{ parameters.tenant_process_type }} ${{ parameters.tenant_name }} ${{ parameters.tenant_size }} ${{ parameters.tenant_localization }} ${{ parameters.tenant_initial_date }}
  displayName: 'npm install and build'
